version: 2
sources:
  - name: olist
    schema: RAW
    database: olist_db
    tables:
      - name: raw_orders
        tests:
        - unique:
            column_name: order_id
        - not_null:
            column_name: order_id
      - name: raw_customers
        tests:
        - unique:
            column_name: customer_id
        - not_null:
            column_name: customer_id  
      - name: raw_products
        tests:
          - unique:
              column_name: product_id
          - not_null:
              column_name: product_id
      - name: raw_order_items
      - name: raw_sellers
      - name: raw_order_payments
      - name: raw_order_reviews
      - name: raw_geolocation
      - name: raw_categories
      - name: PRODUCT_CATEGORY_NAME_TRANSLATION
      - name: raw_weather_rio